#pragma once

typedef enum {
    BADGE_GAME_ART_NONE,
    BADGE_GAME_ART_MUYU,
    BADGE_GAME_ART_VOICE,
    BADGE_GAME_ART_RADIO,
    BADGE_GAME_ART_YAO,
    BADGE_GAME_ART_CUPS,
    BADGE_GAME_ART_MUSE,
} badge_game_art_t;
